var mongoose = require('mongoose');

/*************************************************************
Tentative Schema based on GET trends/places
**************************************************************/

var trendSchema = new mongoose.Schema({
  trend_name : {type: String}, //#SandraBland
  tweet_volume : {type: Number}, //22355
  location_name : {type: String}, //San Francisco
  location_type : {type: String}, //Town or Country
  country : {type: String}, //United States
  country_code : {type: String}, //'US'
  woeid : {type: Number}, //2487956
  parent_woeid : {type: Number}, //23424977
  url : {type: String}, //"http://twitter.com/search?q=%23SandraBland"
  trend_volume: {type: Number}, //Count number of times a country has trending hashtag
  created_at : {type: Date}, //timestamp in UTC generated by Twitter API
  updated_at : {type: Date} //generated by MongoDB
});

var Trend = mongoose.model("Trend", trendSchema);

trendSchema.pre("save", function(next, done) {
  //in case I need to do anything here
  next();
});

// testing entering into db

// var apiObj = {"United States":64,"United Kingdom":27,"Mexico":24,"Japan":22,"India":22,"Russia":20,"Brazil":16,"Korea":15,"Germany":13,"Turkey":13,"Indonesia":12,"Philippines":12,"France":11,"Spain":11,"Venezuela":10,"Canada":9,"Italy":8,"Ukraine":8,"Australia":8,"Malaysia":8,"Poland":7,"Nigeria":7,"South Africa":7,"Saudi Arabia":7,"Vietnam":6,"Pakistan":6,"Argentina":5,"Colombia":5,"Netherlands":5,"Belarus":5,"Chile":4,"Ireland":4,"Switzerland":4,"Egypt":4,"United Arab Emirates":4,"Israel":4,"Ecuador":3,"Norway":3,"Sweden":3,"Greece":3,"Ghana":3,"Kenya":3,"Dominican Republic":2,"Guatemala":2,"Peru":2,"Austria":2,"Latvia":2,"Singapore":2,"Thailand":2,"Algeria":2,"Jordan":2,"Oman":2,"New Zealand":2,"Bahrain":1,"Belgium":1,"Denmark":1,"Kuwait":1,"Lebanon":1,"Panama":1,"Portugal":1,"Qatar":1,"Puerto Rico":1};

// for (var key in apiObj) {
//   new Trend({
//     country: key,
//     trend_volume: apiObj[key]
//   })
//   .save(function(err) {
//     if(err) throw err;
//     console.log('trend saved!');
//   })
// }

module.exports = Trend;
