var db = require('../config');
var mongoose = require('mongoose');

/*************************************************************
Trend Schema for US Towns based on GET trends/places
All towns have the US as their parent WOEID:
All location types are Town

  {
    "name": "United States",
    "placeType": {
      "code": 12,
      "name": "Country"
    },
    "url": "http:\/\/where.yahooapis.com\/v1\/place\/23424977",
    "parentid": 1,
    "country": "United States",
    "woeid": 23424977,
    "countryCode": "US"
  }
**************************************************************/

var usTownTrendSchema = new mongoose.Schema({
  trend_name : {type: String}, //#SandraBland
  tweet_volume : {type: Number}, //22355
  location_name : {type: String}, //San Francisco
  state: {type: String}, //California
  woeid : {type: Number}, //2487956
  url : {type: String}, //"http://twitter.com/search?q=%23SandraBland"
  created_at : {type: Date}, //timestamp in UTC generated by Twitter API
  updated_at : {type: Date} //generated by MongoDB
});

var usTownTrend = mongoose.model("usTownTrend", usTownTrendSchema);

usTownTrendSchema.pre("save", function(next, done) {
  //in case I need to do anything here
  next();
});

module.exports = usTownTrend;